// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzZyTduGPeMUti_au8-suyqGOsxYRO7k',
    appId: '1:1020090244169:web:d6cdfed85769000eb93398',
    messagingSenderId: '1020090244169',
    projectId: 'aidh-chia-cpd-app',
    authDomain: 'aidh-chia-cpd-app.firebaseapp.com',
    storageBucket: 'aidh-chia-cpd-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61GqOYfxMs0DI8N0kY5vMcCla75c3M-A',
    appId: '1:1020090244169:android:f72d7c4ca645d256b93398',
    messagingSenderId: '1020090244169',
    projectId: 'aidh-chia-cpd-app',
    storageBucket: 'aidh-chia-cpd-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWYVdDKH5oM5ekYroJpoU3JnXjzlFCsA',
    appId: '1:1020090244169:ios:63263d46bbacd1c2b93398',
    messagingSenderId: '1020090244169',
    projectId: 'aidh-chia-cpd-app',
    storageBucket: 'aidh-chia-cpd-app.firebasestorage.app',
    iosBundleId: 'com.example.aidhChiaCpdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWYVdDKH5oM5ekYroJpoU3JnXjzlFCsA',
    appId: '1:1020090244169:ios:63263d46bbacd1c2b93398',
    messagingSenderId: '1020090244169',
    projectId: 'aidh-chia-cpd-app',
    storageBucket: 'aidh-chia-cpd-app.firebasestorage.app',
    iosBundleId: 'com.example.aidhChiaCpdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnzZyTduGPeMUti_au8-suyqGOsxYRO7k',
    appId: '1:1020090244169:web:71ada6819ba04ea8b93398',
    messagingSenderId: '1020090244169',
    projectId: 'aidh-chia-cpd-app',
    authDomain: 'aidh-chia-cpd-app.firebaseapp.com',
    storageBucket: 'aidh-chia-cpd-app.firebasestorage.app',
  );
}
